FALLBACK_FIXTURE_DATA = {
    "last_updated": "2026-06-10T10:00:00Z",
    "source": "bundled-fallback",
    "matches": [
        {
            "fixture_id": "fwc2026-001",
            "stage": "GROUP_STAGE",
            "group": "GROUP_A",
            "matchday": 1,
            "home_team": "Mexico",
            "away_team": "South Africa",
            "home_team_code": "MEX",
            "away_team_code": "RSA",
            "kickoff_utc": "2026-06-11T19:00:00Z",
            "duration_minutes": 120,
            "venue": {
                "name": "Mexico City Stadium",
                "city": "Mexico City",
                "country": "Mexico",
            },
            "status": "SCHEDULED",
            "score": None,
            "source_url": "https://www.fifa.com/",
        },
        {
            "fixture_id": "fwc2026-002",
            "stage": "GROUP_STAGE",
            "group": "GROUP_A",
            "matchday": 1,
            "home_team": "Korea Republic",
            "away_team": "Czechia",
            "home_team_code": "KOR",
            "away_team_code": "CZE",
            "kickoff_utc": "2026-06-12T02:00:00Z",
            "duration_minutes": 120,
            "venue": {
                "name": "Guadalajara Stadium",
                "city": "Guadalajara",
                "country": "Mexico",
            },
            "status": "SCHEDULED",
            "score": None,
            "source_url": "https://www.fifa.com/",
        },
        {
            "fixture_id": "fwc2026-r32-001",
            "stage": "LAST_32",
            "group": None,
            "matchday": None,
            "home_team": "Runner-up Group A",
            "away_team": "Runner-up Group B",
            "home_team_code": None,
            "away_team_code": None,
            "kickoff_utc": "2026-06-28T19:00:00Z",
            "duration_minutes": 150,
            "venue": {
                "name": "Los Angeles Stadium",
                "city": "Los Angeles",
                "country": "United States",
            },
            "status": "SCHEDULED",
            "score": None,
            "source_url": "https://www.fifa.com/",
        },
    ],
}

