VENUE_LOOKUP = {
    "football-data:537327": {"name": "Estadio Azteca", "city": "Mexico City", "country": "Mexico"},
    "football-data:537328": {"name": "Estadio Akron", "city": "Guadalajara (Zapopan)", "country": "Mexico"},
    "football-data:537333": {"name": "BMO Field", "city": "Toronto", "country": "Canada"},
    "football-data:537345": {"name": "SoFi Stadium", "city": "Los Angeles (Inglewood)", "country": "United States"},
    "football-data:537334": {"name": "Levi's Stadium", "city": "San Francisco Bay Area (Santa Clara)", "country": "United States"},
    "football-data:537339": {"name": "MetLife Stadium", "city": "New York/New Jersey (East Rutherford)", "country": "United States"},
    "football-data:537340": {"name": "Gillette Stadium", "city": "Boston (Foxborough)", "country": "United States"},
    "football-data:537346": {"name": "BC Place", "city": "Vancouver", "country": "Canada"},
    "football-data:537351": {"name": "NRG Stadium", "city": "Houston", "country": "United States"},
    "football-data:537357": {"name": "AT&T Stadium", "city": "Dallas (Arlington, Texas)", "country": "United States"},
    "football-data:537352": {"name": "Lincoln Financial Field", "city": "Philadelphia", "country": "United States"},
    "football-data:537358": {"name": "Estadio BBVA", "city": "Monterrey (Guadalupe)", "country": "Mexico"},
    "football-data:537369": {"name": "Mercedes-Benz Stadium", "city": "Atlanta", "country": "United States"},
    "football-data:537363": {"name": "Lumen Field", "city": "Seattle", "country": "United States"},
    "football-data:537370": {"name": "SoFi Stadium", "city": "Los Angeles (Inglewood)", "country": "United States"},
    "football-data:537364": {"name": "Hard Rock Stadium", "city": "Miami (Miami Gardens)", "country": "United States"},
    "football-data:537391": {"name": "MetLife Stadium", "city": "New York/New Jersey (East Rutherford)", "country": "United States"},
    "football-data:537392": {"name": "Gillette Stadium", "city": "Boston (Foxborough)", "country": "United States"},
    "football-data:537397": {"name": "GEHA Field at Arrowhead Stadium", "city": "Kansas City", "country": "United States"},
    "football-data:537398": {"name": "Levi's Stadium", "city": "San Francisco Bay Area (Santa Clara)", "country": "United States"},
    "football-data:537403": {"name": "NRG Stadium", "city": "Houston", "country": "United States"},
    "football-data:537409": {"name": "AT&T Stadium", "city": "Dallas (Arlington, Texas)", "country": "United States"},
    "football-data:537410": {"name": "BMO Field", "city": "Toronto", "country": "Canada"},
    "football-data:537404": {"name": "Estadio Azteca", "city": "Mexico City", "country": "Mexico"},
    "football-data:537329": {"name": "SoFi Stadium", "city": "Los Angeles (Inglewood)", "country": "United States"},
    "football-data:537335": {"name": "Mercedes-Benz Stadium", "city": "Atlanta", "country": "United States"},
    "football-data:537336": {"name": "BC Place", "city": "Vancouver", "country": "Canada"},
    "football-data:537330": {"name": "Estadio Akron", "city": "Guadalajara (Zapopan)", "country": "Mexico"},
    "football-data:537348": {"name": "Lumen Field", "city": "Seattle", "country": "United States"},
    "football-data:537342": {"name": "Gillette Stadium", "city": "Boston (Foxborough)", "country": "United States"},
    "football-data:537341": {"name": "Levi's Stadium", "city": "San Francisco Bay Area (Santa Clara)", "country": "United States"},
    "football-data:537347": {"name": "Lincoln Financial Field", "city": "Philadelphia", "country": "United States"},
    "football-data:537359": {"name": "NRG Stadium", "city": "Houston", "country": "United States"},
    "football-data:537353": {"name": "BMO Field", "city": "Toronto", "country": "Canada"},
    "football-data:537354": {"name": "GEHA Field at Arrowhead Stadium", "city": "Kansas City", "country": "United States"},
    "football-data:537360": {"name": "Estadio BBVA", "city": "Monterrey (Guadalupe)", "country": "Mexico"},
    "football-data:537371": {"name": "SoFi Stadium", "city": "Los Angeles (Inglewood)", "country": "United States"},
    "football-data:537365": {"name": "Mercedes-Benz Stadium", "city": "Atlanta", "country": "United States"},
    "football-data:537372": {"name": "BC Place", "city": "Vancouver", "country": "Canada"},
    "football-data:537366": {"name": "Hard Rock Stadium", "city": "Miami (Miami Gardens)", "country": "United States"},
    "football-data:537399": {"name": "AT&T Stadium", "city": "Dallas (Arlington, Texas)", "country": "United States"},
    "football-data:537393": {"name": "Lincoln Financial Field", "city": "Philadelphia", "country": "United States"},
    "football-data:537394": {"name": "MetLife Stadium", "city": "New York/New Jersey (East Rutherford)", "country": "United States"},
    "football-data:537400": {"name": "Levi's Stadium", "city": "San Francisco Bay Area (Santa Clara)", "country": "United States"},
    "football-data:537405": {"name": "NRG Stadium", "city": "Houston", "country": "United States"},
    "football-data:537411": {"name": "Gillette Stadium", "city": "Boston (Foxborough)", "country": "United States"},
    "football-data:537412": {"name": "BMO Field", "city": "Toronto", "country": "Canada"},
    "football-data:537406": {"name": "Estadio Akron", "city": "Guadalajara (Zapopan)", "country": "Mexico"},
    "football-data:537337": {"name": "Lumen Field", "city": "Seattle", "country": "United States"},
    "football-data:537338": {"name": "BC Place", "city": "Vancouver", "country": "Canada"},
    "football-data:537343": {"name": "Hard Rock Stadium", "city": "Miami (Miami Gardens)", "country": "United States"},
    "football-data:537344": {"name": "Mercedes-Benz Stadium", "city": "Atlanta", "country": "United States"},
    "football-data:537331": {"name": "Estadio BBVA", "city": "Monterrey (Guadalupe)", "country": "Mexico"},
    "football-data:537332": {"name": "Estadio Azteca", "city": "Mexico City", "country": "Mexico"},
    "football-data:537355": {"name": "Lincoln Financial Field", "city": "Philadelphia", "country": "United States"},
    "football-data:537356": {"name": "MetLife Stadium", "city": "New York/New Jersey (East Rutherford)", "country": "United States"},
    "football-data:537361": {"name": "AT&T Stadium", "city": "Dallas (Arlington, Texas)", "country": "United States"},
    "football-data:537362": {"name": "GEHA Field at Arrowhead Stadium", "city": "Kansas City", "country": "United States"},
    "football-data:537349": {"name": "Levi's Stadium", "city": "San Francisco Bay Area (Santa Clara)", "country": "United States"},
    "football-data:537350": {"name": "SoFi Stadium", "city": "Los Angeles (Inglewood)", "country": "United States"},
    "football-data:537395": {"name": "BMO Field", "city": "Toronto", "country": "Canada"},
    "football-data:537396": {"name": "Gillette Stadium", "city": "Boston (Foxborough)", "country": "United States"},
    "football-data:537373": {"name": "Estadio Akron", "city": "Guadalajara (Zapopan)", "country": "Mexico"},
    "football-data:537374": {"name": "NRG Stadium", "city": "Houston", "country": "United States"},
    "football-data:537367": {"name": "Lumen Field", "city": "Seattle", "country": "United States"},
    "football-data:537368": {"name": "BC Place", "city": "Vancouver", "country": "Canada"},
    "football-data:537413": {"name": "MetLife Stadium", "city": "New York/New Jersey (East Rutherford)", "country": "United States"},
    "football-data:537414": {"name": "Lincoln Financial Field", "city": "Philadelphia", "country": "United States"},
    "football-data:537407": {"name": "Hard Rock Stadium", "city": "Miami (Miami Gardens)", "country": "United States"},
    "football-data:537408": {"name": "Mercedes-Benz Stadium", "city": "Atlanta", "country": "United States"},
    "football-data:537401": {"name": "GEHA Field at Arrowhead Stadium", "city": "Kansas City", "country": "United States"},
    "football-data:537402": {"name": "AT&T Stadium", "city": "Dallas (Arlington, Texas)", "country": "United States"},
    "football-data:537417": {"name": "SoFi Stadium", "city": "Los Angeles (Inglewood)", "country": "United States"},
    "football-data:537423": {"name": "NRG Stadium", "city": "Houston", "country": "United States"},
    "football-data:537415": {"name": "Gillette Stadium", "city": "Boston (Foxborough)", "country": "United States"},
    "football-data:537418": {"name": "Estadio BBVA", "city": "Monterrey (Guadalupe)", "country": "Mexico"},
    "football-data:537424": {"name": "AT&T Stadium", "city": "Dallas (Arlington, Texas)", "country": "United States"},
    "football-data:537416": {"name": "MetLife Stadium", "city": "New York/New Jersey (East Rutherford)", "country": "United States"},
    "football-data:537425": {"name": "Estadio Azteca", "city": "Mexico City", "country": "Mexico"},
    "football-data:537426": {"name": "Mercedes-Benz Stadium", "city": "Atlanta", "country": "United States"},
    "football-data:537422": {"name": "Lumen Field", "city": "Seattle", "country": "United States"},
    "football-data:537421": {"name": "Levi's Stadium", "city": "San Francisco Bay Area (Santa Clara)", "country": "United States"},
    "football-data:537420": {"name": "SoFi Stadium", "city": "Los Angeles (Inglewood)", "country": "United States"},
    "football-data:537419": {"name": "BMO Field", "city": "Toronto", "country": "Canada"},
    "football-data:537429": {"name": "BC Place", "city": "Vancouver", "country": "Canada"},
    "football-data:537428": {"name": "AT&T Stadium", "city": "Dallas (Arlington, Texas)", "country": "United States"},
    "football-data:537427": {"name": "Hard Rock Stadium", "city": "Miami (Miami Gardens)", "country": "United States"},
    "football-data:537430": {"name": "GEHA Field at Arrowhead Stadium", "city": "Kansas City", "country": "United States"},
    "football-data:537376": {"name": "NRG Stadium", "city": "Houston", "country": "United States"},
    "football-data:537375": {"name": "Lincoln Financial Field", "city": "Philadelphia", "country": "United States"},
    "football-data:537377": {"name": "MetLife Stadium", "city": "New York/New Jersey (East Rutherford)", "country": "United States"},
    "football-data:537378": {"name": "Estadio Azteca", "city": "Mexico City", "country": "Mexico"},
    "football-data:537379": {"name": "AT&T Stadium", "city": "Dallas (Arlington, Texas)", "country": "United States"},
    "football-data:537380": {"name": "Lumen Field", "city": "Seattle", "country": "United States"},
    "football-data:537381": {"name": "Mercedes-Benz Stadium", "city": "Atlanta", "country": "United States"},
    "football-data:537382": {"name": "BC Place", "city": "Vancouver", "country": "Canada"},
    "football-data:537383": {"name": "Gillette Stadium", "city": "Boston (Foxborough)", "country": "United States"},
    "football-data:537384": {"name": "SoFi Stadium", "city": "Los Angeles (Inglewood)", "country": "United States"},
    "football-data:537385": {"name": "Hard Rock Stadium", "city": "Miami (Miami Gardens)", "country": "United States"},
    "football-data:537386": {"name": "GEHA Field at Arrowhead Stadium", "city": "Kansas City", "country": "United States"},
    "football-data:537387": {"name": "AT&T Stadium", "city": "Dallas (Arlington, Texas)", "country": "United States"},
    "football-data:537388": {"name": "Mercedes-Benz Stadium", "city": "Atlanta", "country": "United States"},
    "football-data:537389": {"name": "Hard Rock Stadium", "city": "Miami (Miami Gardens)", "country": "United States"},
    "football-data:537390": {"name": "MetLife Stadium", "city": "New York/New Jersey (East Rutherford)", "country": "United States"},
}
